### ISSUE TITLE
App Crashed due to removeActivityDelegate method 

### ISSUE THREAD

**Issue by vishal5115** [B3nedikt/ViewPump#15]
java.lang.NoSuchMethodError: No static method removeActivityDelegate(Landroidx/appcompat/app/AppCompatDelegate;)V in class Landroidx/appcompat/app/AppCompatDelegate; or its super classes (declaration of 'androidx.appcompat.app.AppCompatDelegate' appears in /data/app/com.apporio.all_in_one-02R9Oz2ZxqgzLL4-WfJLXw==/base.apk!classes6.dex)

Note: I already set implementation 'androidx.appcompat:appcompat:1.2.0'. But internally it set version 1.3.0-alpha
I tried by clean, Invalidate ,delete .gradle file, caches and .idea file . But nothing works

**Comment by B3nedikt** [comment]
While I would recommend using appcompat 1.2.0, the exact version is not a requirement, the lib has also been tested with 1.3.0-beta01, as well as version older then 1.2.0. So this should not be the reason for this crash in theory.

To reproduce this issue I would need some more input. Can you try to fork this repository and modify the example app so it reproduces the issue?

If this is not possible for you, please post the exact versions of the dependencies your project uses.
I suspect this crash is a configuration problem maybe related to your proguard configuration or the dependencies you use.

**Comment by vishal5115** [comment]
Hi,
When we implement 1.3.0-alpha01 in project then  removeActivityDelegate(this) method from AppCompatDelegateWrapper class is not find in AppCompatDelegate class. So if I implement library then it's impossible for me to change this method.

**Comment by vishal5115** [comment]
I forked repo and commited please check

**Comment by B3nedikt** [comment]
Okay, it seems google removed this method in 1.3.0-alpha01, only to add it again later. I am pretty sure this was not intentional ;) So just updating to 1.3.0-beta01 should fix it for you. If you can I would recommend using the stable version 1.2.0 though.
