### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by prateekvijay** [B3nedikt/ViewPump#24]
Fatal Exception: java.lang.IllegalAccessError
Interface androidx.core.widget.m implemented by class androidx.appcompat.widget.AppCompatImageView is inaccessible (declaration of 'androidx.appcompat.widget.AppCompatImageView' appears in /data/app/com.peoplehum.app-slX_HKD2XHILJr3zUTe2Sg==/base.apk)

dev.b3nedikt.viewpump.internal.InterceptorChain.proceed (InterceptorChain.java:26)
dev.b3nedikt.reword.RewordInterceptor.intercept (RewordInterceptor.java:34)
dev.b3nedikt.viewpump.internal.InterceptorChain.proceed (InterceptorChain.java:37)
androidx.appcompat.app.ViewPumpAppCompatDelegate.inflate (ViewPumpAppCompatDelegate.java:104)

android.view.LayoutInflater.inflate (LayoutInflater.java:374)
com.peoplehum.app.customview.CustomProgressBar.init (CustomProgressBar.java:29)
com.peoplehum.app.base.BaseActivity.onCreate (BaseActivity.java:185)
com.peoplehum.app.base.SplashScreenActivity.onCreate (SplashScreenActivity.java:58)

**Comment by B3nedikt** [comment]
@prateekvijay I am pretty sure this is not related to ViewPump, I assume a incorrect gradle/proguard configuration. Always use the latest versions when possible. If you think this is related though, try to recreate the issue with the example application in this repository, or with the one in my reword repository. Then link the fork to this issue and reopen it :)
