### ISSUE TITLE
What are the main differences between this and "https://github.com/InflationX/ViewPump" ?

### ISSUE THREAD

**Issue by Nancy945** [B3nedikt/ViewPump#32]
I found two similar projects, can you tell me the main differences.

**Comment by B3nedikt** [comment]
Mine is a fork, which has a ton of issues fixed regarding web views and compatibility with googles "appcompat" library. If you tell me more about what you want to do with ViewPump, I could tell you if it would be a good fit for your use case ;)

**Comment by Nancy945** [comment]
Thanks for the answer. I don't have a specific question, I'm currently researching powerful localization libraries that I've found, and seeing that it's not stated in the readme.
